### ISSUE TITLE
Fix people and groups pages

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/bioschemas.github.io#37]
Various changes in bioschemas mean that the groups and people pages are not working correctly.

**Comment by AlasdairGray** [comment]
Groups still appear in the data types table in the specification page.

**Comment by kcmcleod** [comment]
groups column removed from data types table & pushed to kcmChanges branch

can this be closed now?

**Comment by AlasdairGray** [comment]
Need to merge with master as there were changes made to include governance. 

Have you checked the people page on a mobile view? Can you make the number of columns dependent on whether it is desktop (using 4) or mobile (use 1)?

**Comment by kcmcleod** [comment]
merged and pushed update that attempts to determine device and change number of columns accordingly. HOWEVER, doing this is not especially reliable... need to investigate a more robust solution

**Comment by AlasdairGray** [comment]
Can you use the same mechanism that is used by the navbar?

**Comment by kcmcleod** [comment]
they seem to be deciding based on width of screen, which is less reliable. 
some of the liquid templates have this functionality built in, they use the same approach i did...

**Comment by AlasdairGray** [comment]
Seems to be working. I've pushed this to the main site
d5e5015eb35f1d554937dac814cdfdc99c34995e
