### ISSUE TITLE
Clean up navigation files 

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/bioschemas.github.io#40]
The _includes directory contains a lot of files that are no longer used. Only the navbar and mobile navbar files are currently used.

**Comment by kcmcleod** [comment]
the following are required: 
* about_nav.html
* collections_footer.html
* examples_nav.html
* footer.html
* head.html
* header.html
* mobile_navbar.html
* navbar.html
* projects_nav.html

all other files have been removed

**Comment by AlasdairGray** [comment]
I'm curious where about_nav, examples_nav, and projects_nav are used. Shouldn't they be replaced with the navbar.html?

**Comment by AlasdairGray** [comment]
The about layout is the only file using the about_nav. It does not seem to be a live page.

**Comment by kcmcleod** [comment]
The question is do we care about deep links? 

about_nav.html is used by _layout/about.html, which in turn is used by about/index.html. So we can delete all files or none of them.

These are not used by on the current site, but how confident are we that other sites are not linking to these pages? Do we care if they are linking?

The same is true for examples_nav & projects_nav... want me to just slash & burn or to be more conservative?

**Comment by AlasdairGray** [comment]
We have a jekyll extension enabled that can be used to redirect old pages to new locations

**Comment by AlasdairGray** [comment]
See _meetings/2017-10_AdoptionMeeting.html for an instance of its usage
