### ISSUE TITLE
Broken links: standard row in profile table is mostly 404s

### ISSUE THREAD

**Issue by kcmcleod** [BioSchemas/bioschemas.github.io#41]
@AlasdairGray In the profiles table, the row for standard is mostly 404s. Only the link to the GitHub issues works. What do you want to happen?
* remove the row
* grey out the bad links
* have empty cells instead of greyed out
* or ...

**Comment by AlasdairGray** [comment]
We really need to get the editors staging area set up and then we could move the standards over to that until we have some sort of initial version.

@guicalman how are you progressing with the staging area, or should we just clone the specification area for now?

**Comment by kcmcleod** [comment]
no longer relevant
