### ISSUE TITLE
Staging and specification pages

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/bioschemas.github.io#42]
Currently we have the following columns for a profile on the specification page:
- Name
- Description
- Spec.
- Folder
- Mapping
- Use Cases
- Tasks and Issues
- Examples

I'm not convinced all of these should be on the specification page. They should all be on the staging page, but for the specification page, I think that we should only have
- Name
- Description
- Spec.
- Use Cases
- Tasks and Issues
- Examples

Although I'm not entirely sure about the use cases.

**Comment by kcmcleod** [comment]
done
