### ISSUE TITLE
Move additionalType to recommended or optional

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/bioschemas.github.io#53]
Once @kcmcleod has add SIO:011119 as rdf:type, additionalType should be moved to recommended or optional. @otienoanyango please update https://github.com/BioSchemas/bioschemas.github.io/blob/master/_devSpecs/ProteinStructure/specification.html to reflect this.

**Comment by kcmcleod** [comment]
@otienoanyango - added SIO:011119 as rdf:type & updated description for additionalType. Willing to move it too, if you can tell me where it goes: optional or recommended?

**Comment by ljgarcia** [comment]
@otienoanyango could you please let @kcmcleod whether additionaltype should be moved to recommended or optional? thanks. I will assign this issue to you, please reassign to @kcmcleod whenever you have let him know.

**Comment by otienoanyango** [comment]
@kcmcleod - This is ok. I haven't found a better ontology yet.

**Comment by kcmcleod** [comment]
Moved to recommended following instruction
