### ISSUE TITLE
Protein structure transcribed from gene?

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/bioschemas.github.io#54]
@otienoanyango is protein structure transcribed from a gene? If the protein structure is linked to a protein, there is no need to have the transcribed gene at this level. Please double check.

**Comment by otienoanyango** [comment]
No it is not. It is the protein(s) defined in the structure that are transcribed from gene.

**Comment by ljgarcia** [comment]
@otienoanyango then please take a look at http://bioschemas.org/specifications/ProteinStructure/specification/ and make the necessaries updates. @kcmcleod can tell you where to make / how to communicate those changes

**Comment by kcmcleod** [comment]
@otienoanyango please look at the DRAFT specification:
http://bioschemas.org/devSpecs/ProteinStructure/specification/

you can make changes directly by editing this file:
https://github.com/BioSchemas/bioschemas.github.io/blob/master/_devSpecs/ProteinStructure/specification.html

or you can send a list of changes to me and I'll change it for you.

**Comment by otienoanyango** [comment]
I have got rid of this property in the BiochemEntity definition for Protein Structure. we strictly defined it in the context of a protein.
