### ISSUE TITLE
isContainedIn instead organism?

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/bioschemas.github.io#55]
@otienoanyango BioChemEntity has a property isContainedIn (equivalent to isPartOf as described in the Relation Ontology) that can be used to link a protein structure to the corresponding organism. Also, if the protein structure corresponds to a protein and the proteins corresponds to an organism, do you need organism at this level?

**Comment by kcmcleod** [comment]
moved to https://github.com/BioSchemas/specifications/issues/147
