### ISSUE TITLE
Find a better way to communicate the selected type for profiles

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/bioschemas.github.io#58]
Recently, rdf:type was added to the profile specifications but this seems to be confusing, we got questions about it during the Samples meeting last Thu & Fri. The rdf:type is not only the one for the profile, as the BioChemEntity type (or whichever corresponds to the actual type) is also an rdf:type.

Maybe somehow as part of the hierarchy?

**Comment by kcmcleod** [comment]
this has been moved to specifications repo issue number 146. please update/extend it there.
