### ISSUE TITLE
Find a way to include modifications to existing elements in schema.org

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/bioschemas.github.io#59]
We have pages for new types and profiles. However, we have also suggested some changes to existing elements in schema.org, those should be available somewhere on the Bioschemas pages so we keep them in mind for the final proposal.

For instance, we proposed isBasisFor (opposite of basedOn) for CreativeWork. 

@Kerruba I think you have a modification as well for CategoryCode, could you please added that one to this thread so we keep them together? This would make things easier for @AlasdairGray (or whoever is the final assignee) to capture them.

Thanks

**Comment by kcmcleod** [comment]
moved issue to specifications repo (issue number 145). please update/extend it there.
